### ISSUE TITLE
Contact information ? 

### ISSUE THREAD

**Issue by mbertalan** [smoeding/usl#4]
Hej Stefan,

Do you have an email ? Unfortunately, I could not find any way to contact you at GitHub and in your blog. 

Best,

Marcelo

**Comment by smoeding** [comment]
Hi Marcelo,

for the USL package: there is an email in the DESCRIPTION file (as required by CRAN).
for my blog: the email is available behind the "Imprint" menu (as required by local law).

Regards,
Stefan

**Comment by smoeding** [comment]
Question has been answered.

Success with your research!

**Comment by mbertalan** [comment]
Thanks !

Marcelo Bertalan.
